CREATE TABLE annotation (
	"CHROM" VARCHAR, /*MOD*/ 
	"POS" DECIMAL, /*MOD*/
	"REF" VARCHAR, /*MOD*/
	"ALT" VARCHAR, /*MOD*/
	"Gene" VARCHAR, 
	"Gene Full Name" VARCHAR, 
	"Chrom/Position" VARCHAR, 
	"Change" VARCHAR, 
	"Filter" BOOLEAN, 
	"Mapping Quality (MQ)" DECIMAL, 
	"Genotype" VARCHAR, 
	"Frequency" VARCHAR, /*MOD*/
	"GQ Score" DECIMAL, 
	"Ref Depth" DECIMAL, 
	"Alt Depth" DECIMAL, 
	"Top Consequence" VARCHAR, 
	"Consequence" VARCHAR, 
	"Impact" VARCHAR, 
	"Splice Site" VARCHAR, 
	"Max. Population Frequency" DECIMAL, 
	"Max. Sub-Population Frequency" DECIMAL, 
	"ClinVar Evaluation" VARCHAR, 
	"ClinVar Phenotype" VARCHAR, 
	"OMIM" VARCHAR, 
	"HPO Phenotype" VARCHAR, 
	"pLI" DECIMAL, 
	"SIFT" VARCHAR, 
	"PolyPhen" VARCHAR, 
	"Effect Prediction" VARCHAR, 
	"Effect Score" DECIMAL, 
	"CADD Conservation" DECIMAL, 
	"Intolerance" VARCHAR, /*MOD*/ 
	"GERP++ Score" DECIMAL, 
	"PhyloP46 Conservation" VARCHAR, 
	"PhyloP46 Conservation Score" DECIMAL, 
	"HGVS (RefGene)" VARCHAR, 
	"HGVS (VEP)" VARCHAR, 
	"Gene Family" VARCHAR, /*MOD*/
	"Gene Description" VARCHAR, 
	"GO Function" VARCHAR, 
	"GO Cell Component" VARCHAR, 
	"GO Pathway" VARCHAR, 
	"Literature" VARCHAR, 
	"COSMIC" VARCHAR, 
	"Regulatory" VARCHAR, 
	"Interpro" VARCHAR, 
	"Splicing dbscSNV11" DECIMAL, 
	"M-CAP Pathogenicity Score" DECIMAL, 
	"REVEL Pathogenicity Score" DECIMAL, 
	"regSNP-intron Pathogenicity" VARCHAR, 
	"Spidex Zscore" DECIMAL, 
	"Spidex Max Tissue" DECIMAL, 
	"dbSNP" VARCHAR, 
	"Cytoband" VARCHAR, 
	"SegDup" VARCHAR, 
	"NHLBI" DECIMAL, 
	"1000G" DECIMAL, 
	"Yale V2" DECIMAL, 
	"Yale MedExome" DECIMAL, 
	"gnomAD Genome" DECIMAL, 
	"gnomAD Exome" DECIMAL, 
	"gnGen (AFR)" DECIMAL, 
	"gnGen (AMR)" DECIMAL, 
	"gnGen (ASJ)" DECIMAL, 
	"gnGen (EAS)" DECIMAL, 
	"gnGen (FIN)" DECIMAL, 
	"gnGen (NFE)" DECIMAL, 
	"gnGen (OTH)" DECIMAL, 
	"gnGen (SAS)" DECIMAL, 
	"gnEx (AFR)" DECIMAL, 
	"gnEx (AMR)" DECIMAL, 
	"gnEx (ASJ)" DECIMAL, 
	"gnEx (EAS)" DECIMAL, 
	"gnEx (FIN)" DECIMAL, 
	"gnEx (NFE)" DECIMAL, 
	"gnEx (OTH)" DECIMAL, 
	"gnEx (SAS)" DECIMAL, 
	"SIFT Score" DECIMAL, 
	"SIFT Prediction" VARCHAR, 
	"Polyphen2 HDIV Score" DECIMAL, 
	"Polyphen2 HDIV Prediction" VARCHAR, 
	"Polyphen2 HVAR Score" DECIMAL, 
	"Polyphen2 HVAR Prediction" VARCHAR, 
	"FATHMM Score" DECIMAL, 
	"FATHMM Prediction" VARCHAR, 
	"MetaSVM Score" DECIMAL, 
	"MetaSVM Prediction" VARCHAR, 
	"LRT Score" DECIMAL, 
	"LRT Prediction" VARCHAR, 
	"MutationTaster Score" DECIMAL, 
	"MutationTaster Prediction" VARCHAR, 
	"MutationAssessor Score" DECIMAL, 
	"MutationAssessor Prediction" VARCHAR, 
	"MetaLR Score" DECIMAL, 
	"MetaLR Prediction" VARCHAR, 
	"PROVEAN Score" DECIMAL, 
	"PROVEAN Prediction" VARCHAR, 
	"VEST3 Score" DECIMAL, 
	"PhyloP 46-way Score" DECIMAL, 
	"PhyloP100 Vertebrate" DECIMAL, 
	"PhyloP20 Mammalian" DECIMAL, 
	"PhyloP46 Conservation_2" VARCHAR, 
	"PhyloP46 Conservation Score_2" DECIMAL, 
	"SiPhy29 Odds" DECIMAL
);
